#! /bin/bash
uglifyjs \
src/utilities/webglContext.js \
src/utilities/mouse.js \
src/utilities/path.js \
src/observableData.js \
src/attachedObject.js \
src/attachedObjectCollection.js \
src/shader.js \
src/dcmSeries.js \
src/viewer.js \
src/generateGrid.js \
src/pane.js \
src/selection.js \
src/behaviors/behavior.js \
src/behaviors/compositeBehavior.js \
src/behaviors/mouseBehaviors/capturedMouseBehavior.js \
src/behaviors/mouseBehaviors/buttonCapturedMouseBehavior.js \
src/behaviors/mouseBehaviors/WWWLBehavior.js \
src/behaviors/mouseBehaviors/selectBehavior.js \
src/behaviors/mouseBehaviors/selectShapeBehavior.js \
src/behaviors/mouseBehaviors/zoomBehavior.js \
src/behaviors/mouseBehaviors/panBehavior.js \
src/behaviors/mouseBehaviors/pageBehavior.js \
src/behaviors/mouseBehaviors/wheelPageBehavior.js \
src/shapes/line.js \
src/behaviors/mouseBehaviors/insertLineBehavior.js \
src/behaviors/mouseBehaviors/pixelInfoBehavior.js \
src/behaviors/touchBehaviors/WWWLBehavior.js \
src/behaviors/touchBehaviors/zoomBehavior.js \
src/behaviors/touchBehaviors/panBehavior.js \
src/commands/command.js \
src/commands/rotateCommand.js \
src/commands/flipCommand.js \
src/overlays/overlay.js \
src/overlays/cornerInfoOverlay.js \
src/overlays/scaleOverlay.js \
src/overlays/shapeOverlay.js \
src/overlays/topOverlay.js \
-o libs/dicom.min.js
